CREATE TABLE IF NOT EXISTS comprehensive_report_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    report_id VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NULL,
    doctor_name VARCHAR(255) NULL,
    disease_type VARCHAR(255) NULL,
    questionnaire_batch_id VARCHAR(64) NULL,
    questionnaire_record_ids_json LONGTEXT NULL,
    questionnaire_names_json LONGTEXT NULL,
    questionnaire_completed_at DATETIME NULL,
    tongue_report_id VARCHAR(64) NULL,
    tongue_created_at DATETIME NULL,
    report_text LONGTEXT NULL,
    source_info_json LONGTEXT NULL,
    source_basis_json LONGTEXT NULL,
    report_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    model_name VARCHAR(128) NULL,
    prompt_version VARCHAR(32) NULL,
    error_msg TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_comprehensive_report_id (report_id),
    KEY idx_comprehensive_report_patient_created (patient_id, created_at),
    KEY idx_comprehensive_report_doctor_created (doctor_id, created_at),
    KEY idx_comprehensive_report_status_created (report_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
